name: Build and Push Debezium Connector Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push to Google Artifact Registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 참조 워크플로우와 동일하게 서비스 계정 키를 사용하여 GCP에 인증합니다.
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # KCR/DockerHub 등 컨테이너 레지스트리 로그인
      - name: Login to Container Registry
        run: echo "${{ secrets.KCR_PASSWORD }}" | docker login ${{ secrets.KCR_HOST }} -u ${{ secrets.KCR_USER }} --password-stdin

      - name: Configure Docker for Google Artifact Registry
        run: gcloud auth configure-docker asia-northeast3-docker.pkg.dev

      - name: Pull, Tag, and Push Confluent Init Image
        run: |
          docker pull confluentinc/cp-server-connect-init:7.4.0
          docker tag confluentinc/cp-server-connect-init:7.4.0 asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/mcp-marcket-artifact-registry/cp-server-connect-init:7.4.0
          docker push asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/mcp-marcket-artifact-registry/cp-server-connect-init:7.4.0

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/mcp-marcket-artifact-registry/connect:latest
            asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/mcp-marcket-artifact-registry/connect:${{ github.sha }}